# Generated by Django 5.0.2 on 2024-03-05 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'estados',
            },
        ),
        migrations.AlterModelTable(
            name='cargo',
            table='cargo',
        ),
        migrations.AlterModelTable(
            name='habilitado',
            table='habilitado',
        ),
        migrations.AlterModelTable(
            name='perfil',
            table='perfil',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_insumo', models.CharField(max_length=30)),
                ('fecha_vencimiento', models.DateField()),
                ('cantidad_existente', models.IntegerField()),
                ('cantidad_minimo', models.IntegerField()),
                ('fk_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.categoria')),
                ('fk_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.estado')),
            ],
            options={
                'db_table': 'insumos',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=40)),
                ('tamaño', models.CharField(max_length=40)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fk_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.estado')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Producto_Insumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.insumo')),
                ('fk_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.producto')),
            ],
            options={
                'db_table': 'productos_insumos',
            },
        ),
    ]
