# Generated by Django 5.0.2 on 2024-03-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_estado_pedido_pedido_pedido_producto_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_producto',
            name='precio_producto',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
