# Generated by Django 5.0.2 on 2024-03-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_categoria_estado_alter_cargo_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='insumos',
            field=models.ManyToManyField(related_name='productos', to='cliente.insumo'),
        ),
        migrations.DeleteModel(
            name='Producto_Insumos',
        ),
    ]
