# Generated by Django 5.0.2 on 2024-03-15 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-id']},
        ),
    ]
