# Generated by Django 5.0.2 on 2024-03-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_alter_pedido_fecha_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='cantidad_existente',
            field=models.BigIntegerField(),
        ),
    ]
