# Generated by Django 5.0.2 on 2024-03-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_alter_insumo_cantidad_existente'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada_insumo',
            name='cantidad_inicial',
            field=models.BigIntegerField(null=True),
        ),
    ]
