# Generated by Django 5.0.2 on 2024-03-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_entrada_insumo_cantidad_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(null=True, upload_to='perfiles'),
        ),
    ]
