# Generated by Django 5.0.2 on 2024-03-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0009_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(default='perfiles/imagen_usuario.jpg', null=True, upload_to='perfiles'),
        ),
    ]
