# Generated by Django 5.0.2 on 2024-03-20 03:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0010_alter_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada_insumo',
            name='fecha_entrada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='entrada_insumo',
            name='fecha_vencimiento',
            field=models.DateTimeField(),
        ),
    ]
